### ISSUE TITLE
Allow sorting the ingredient list by mod name and by alphabetical order

### ISSUE THREAD

**Issue by RepoDraghon** [mezz/JustEnoughItems#1582]
1.12.2 How can I get the items to list 1st by Mod then Alphabetically?

**Comment by IMarvinTPA** [comment]
I have a fork that can do this (and also has an API for Inventory Tweaks.)
My old bug: https://github.com/mezz/JustEnoughItems/issues/549
My pull request: https://github.com/mezz/JustEnoughItems/pull/1623
My repo: https://github.com/IMarvinTPA/JustEnoughItems/tree/1.12_sorting

**Comment by Drullkus** [comment]
NEI had a system where you could set tiers of sorting priority, so you could first sort by color bottommost, then item name on the middle, then mod ID topmost, creating a bottom-to-top sorting priority list. Would be nice if a such thing existed here too :)

**Comment by mezz** [comment]
I have added a config for this in the latest version for 1.16.3. https://github.com/mezz/JustEnoughItems/commit/71c507b164934d84d712a2e944beb45ec080e2fb

In the config file `jei-client.toml` see this section:
```toml
[sorting]
	#Sorting order for the ingredient list. Valid stages: [MOD_NAME, INGREDIENT_TYPE, ALPHABETICAL, CREATIVE_MENU]
	IngredientSortStages = ["MOD_NAME", "INGREDIENT_TYPE", "CREATIVE_MENU"]
```
You can now change it to sort using `ALPHABETICAL` order instead of `MOD_NAME` and `CREATIVE_MENU` order.
