### ISSUE TITLE
Color search seems to be not working

### ISSUE THREAD

**Issue by Firefly0402** [mezz/JustEnoughItems#2502]
I set the color search to "require prefix" but I can't search for colors. There are always no items found. I checked my spelling, I tried "enabled" mode. Nothing seems to make it work :(
Can't find a config on the server though. My client config adopts/changes according to all changes I make ingame but still can't search for colors.

EDIT: I'm playing on an Enigmatica 6 Server (Version 0.5.14) using JEI Version 1.16.5-7.7.1.121

**Comment by mezz** [comment]
Thanks for the report!
It seems to be working fine for me with just JEI 7.7.1.
<img width="966" alt="Screen Shot 2021-10-01 at 6 01 35 PM" src="https://user-images.githubusercontent.com/916092/135703017-1e7e1c04-392d-452c-b9e0-7fcd52ee72f2.png">

Maybe your `[colors]` section in the config got messed up somehow?
Try with these configs:
```toml

[advanced]
	#How items should be handed to you
	#Allowed Values: INVENTORY, MOUSE_PICKUP
	GiveMode = "MOUSE_PICKUP"
	#Debug mode enabled
	DebugMode = false
	#Display search bar in the center
	CenterSearch = false
	#Max. recipe gui height
	#Range: > 175
	RecipeGuiHeight = 350
	#Set low-memory mode (makes search very slow, but uses less RAM)
	LowMemorySlowSearchEnabled = false
	#Max number of columns shown
	#Range: 4 ~ 100
	MaxColumns = 9

[colors]
	#Color values to search for
	SearchColors = ["White:EEEEEE", "LightBlue:7492cc", "Cyan:00EEEE", "Blue:2222dd", "LapisBlue:25418b", "Teal:008080", "Yellow:cacb58", "GoldenYellow:EED700", "Orange:d97634", "Pink:D1899D", "HotPink:FC0FC0", "Magenta:b24bbb", "Purple:813eb9", "JadedPurple:43324f", "EvilPurple:2e1649", "Lavender:B57EDC", "Indigo:480082", "Sand:dbd3a0", "Tan:bb9b63", "LightBrown:A0522D", "Brown:634b33", "DarkBrown:3a2d13", "LimeGreen:43b239", "SlimeGreen:83cb73", "Green:008000", "DarkGreen:224d22", "GrassGreen:548049", "Red:963430", "BrickRed:b0604b", "NetherBrick:2a1516", "Redstone:ce3e36", "Black:181515", "CharcoalGray:464646", "IronGray:646464", "Gray:808080", "Silver:C0C0C0"]

[sorting]
	#Sorting order for the ingredient list. Valid stages: [MOD_NAME, INGREDIENT_TYPE, ALPHABETICAL, CREATIVE_MENU, TAG, TOOL_TYPE, WEAPON_DAMAGE, ARMOR, MAX_DURABILITY]
	IngredientSortStages = ["MOD_NAME", "INGREDIENT_TYPE", "CREATIVE_MENU", "ALPHABETICAL", "WEAPON_DAMAGE", "TOOL_TYPE", "ARMOR", "TAG"]

[search]
	#Search mode for Mod Names (prefix: @)
	#Allowed Values: ENABLED, REQUIRE_PREFIX, DISABLED
	ModNameSearchMode = "REQUIRE_PREFIX"
	#Search mode for Tag Names (prefix: $)
	#Allowed Values: ENABLED, REQUIRE_PREFIX, DISABLED
	TagSearchMode = "REQUIRE_PREFIX"
	#Search mode for Creative Tab Names (prefix: %)
	#Allowed Values: ENABLED, REQUIRE_PREFIX, DISABLED
	CreativeTabSearchMode = "DISABLED"
	#Search mode for Colors (prefix: ^)
	#Allowed Values: ENABLED, REQUIRE_PREFIX, DISABLED
	ColorSearchMode = "ENABLED"
	#Search mode for resources IDs (prefix: &)
	#Allowed Values: ENABLED, REQUIRE_PREFIX, DISABLED
	ResourceIdSearchMode = "DISABLED"
	#Search mode for Tooltips (prefix: #)
	#Allowed Values: ENABLED, REQUIRE_PREFIX, DISABLED
	TooltipSearchMode = "ENABLED"
	#Search advanced tooltips (visible with F3+H)
	SearchAdvancedTooltips = false

[modname]
	#Formatting for mod name tooltip
	#Use these formatting keys:
	#black, dark_blue, dark_green, dark_aqua, dark_red, dark_purple, gold, gray, dark_gray, blue, green, aqua, red, light_purple, yellow, white
	#obfuscated, bold, strikethrough, underline, italic
	ModNameFormat = "blue italic"
```
