### ISSUE TITLE
[Bug]: 1.18.2 (Parts of the) JEI Config... gone? (Forge 40.2.0)

### ISSUE THREAD

**Issue by xFirefalconx** [mezz/JustEnoughItems#3139]
### Steps to Reproduce the Bug

Open inventory, press jei config button. Try to find the settings for item columns/rows. Can't find it? Welcome to my issue. 

I just updated to 10.2.1.1002 after a mod update needed it. Now I look at my interface and it has shrunk beack to default which I really don't like. I tried to change that and only found server options about cheats? Utterly confused. 

**Edit: Update to jei-1.18.2-forge-10.2.1.1004 - issue persists.** 

### Expected Behavior

Old config option OR an other option to resize the item window...

### Actual Behavior

For some reasons the options are not present. 
I am not sure if this is caused by multiplayer, but even trying to access it via the mods window was not possible. 

### Extra Notes (Optional)

This happened after I updated Chunk by Chunk and More Overlays Updated to their latest (/beta) versions. I though feel like this has nothing to with my custom wip modpack. I had the configs before the JEI update, as well.
The amount of mods is 190 in total. Let me know if that's relevant but not visible in the latest.log, I'll append it then.

Edit: I use Configured 2.0.0.

### latest.log

https://gist.github.com/xFirefalconx/bf0579aa98a4b2b9a1e28a655e27c352

**Comment by Daraphin** [comment]
Hello exactly same problem, all local configs are gone, i tried to download the mod with different version, made new modpack etc. but nothing bring confiigs back

**Comment by xFirefalconx** [comment]
Wonder if this relates to https://github.com/mezz/JustEnoughItems/issues/1526

Currently missing a changelog in the Curseforge App to whereas what was improved/fixed in the latest two updates since I posted this bug report. Latest version in there shows "Current release 7.7.1.153" which is... outdated I assume.

**Comment by xFirefalconx** [comment]
Did some more digging. The file I found in the config folder after updating:

jei version: 
jei-1.18.2-forge-10.2.1.1004

file name: 
jei-client.toml
```toml
[advanced]
	#How items should be handed to you
	#Allowed Values: INVENTORY, MOUSE_PICKUP
	GiveMode = "MOUSE_PICKUP"
	#Debug mode enabled
	DebugMode = false
	#Enable cheating items into the hotbar by using the shift+number keys.
	CheatToHotbarUsingHotkeysEnabled = false
	#Display search bar in the center
	CenterSearch = false
	#Max. recipe gui height
	#Range: > 175
	RecipeGuiHeight = 350
	#Set low-memory mode (makes search very slow, but uses less RAM)
	LowMemorySlowSearchEnabled = false

[colors]
	#Color values to search for
	SearchColors = ["White:EEEEEE", "LightBlue:7492cc", "Cyan:00EEEE", "Blue:2222dd", "LapisBlue:25418b", "Teal:008080", "Yellow:cacb58", "GoldenYellow:EED700", "Orange:d97634", "Pink:D1899D", "HotPink:FC0FC0", "Magenta:b24bbb", "Purple:813eb9", "JadedPurple:43324f", "EvilPurple:2e1649", "Lavender:B57EDC", "Indigo:480082", "Sand:dbd3a0", "Tan:bb9b63", "LightBrown:A0522D", "Brown:634b33", "DarkBrown:3a2d13", "LimeGreen:43b239", "SlimeGreen:83cb73", "Green:008000", "DarkGreen:224d22", "GrassGreen:548049", "Red:963430", "BrickRed:b0604b", "NetherBrick:2a1516", "Redstone:ce3e36", "Black:181515", "CharcoalGray:464646", "IronGray:646464", "Gray:808080", "Silver:C0C0C0"]

[sorting]
	#Sorting order for the ingredient list. Valid stages: [MOD_NAME, INGREDIENT_TYPE, ALPHABETICAL, CREATIVE_MENU, TAG, TOOL_TYPE, WEAPON_DAMAGE, ARMOR, MAX_DURABILITY]
	IngredientSortStages = ["MOD_NAME", "INGREDIENT_TYPE", "CREATIVE_MENU", "ALPHABETICAL", "WEAPON_DAMAGE", "TOOL_TYPE", "ARMOR", "TAG"]

[search]
	#Search mode for Mod Names (prefix: @)
	#Allowed Values: ENABLED, REQUIRE_PREFIX, DISABLED
	ModNameSearchMode = "ENABLED"
	#Search mode for Tag Names (prefix: $)
	#Allowed Values: ENABLED, REQUIRE_PREFIX, DISABLED
	TagSearchMode = "REQUIRE_PREFIX"
	#Search mode for Creative Tab Names (prefix: %)
	#Allowed Values: ENABLED, REQUIRE_PREFIX, DISABLED
	CreativeTabSearchMode = "DISABLED"
	#Search mode for Colors (prefix: ^)
	#Allowed Values: ENABLED, REQUIRE_PREFIX, DISABLED
	ColorSearchMode = "DISABLED"
	#Search mode for Tooltips (prefix: #)
	#Allowed Values: ENABLED, REQUIRE_PREFIX, DISABLED
	TooltipSearchMode = "ENABLED"
	#Search advanced tooltips (visible with F3+H)
	SearchAdvancedTooltips = true
	#Search mode for resources locations (prefix: &)
	#Allowed Values: ENABLED, REQUIRE_PREFIX, DISABLED
	ResourceLocationSearchMode = "DISABLED"

[modname]
	#Formatting for mod name tooltip
	#Use these formatting colors:
	#black, dark_blue, dark_green, dark_aqua, dark_red, dark_purple, gold, gray, dark_gray, blue, green, aqua, red, light_purple, yellow, white
	#With these formatting options:
	#obfuscated, bold, strikethrough, underline, italic
	ModNameFormat = "blue italic"

[IngredientList]
	#Max number of rows shown
	#Range: 1 ~ 100
	MaxRows = 24
	#Max number of columns shown
	#Range: 4 ~ 100
	MaxColumns = 16
	#Horizontal alignment of the ingredient grid inside the available area
	#Allowed Values: LEFT, CENTER, RIGHT
	HorizontalAlignment = "RIGHT"
	#Horizontal alignment of the ingredient grid inside the available area
	#Allowed Values: TOP, CENTER, BOTTOM
	VerticalAlignment = "TOP"
	#Visibility of the top page buttons. Use AUTO_HIDE to only show it when there are multiple pages.
	#Allowed Values: ENABLED, AUTO_HIDE, DISABLED
	ButtonNavigationVisibility = "ENABLED"
	#Set to true to draw a background texture behind the gui.
	DrawBackground = false

[BookmarkList]
	#Max number of rows shown
	#Range: 1 ~ 100
	MaxRows = 16
	#Max number of columns shown
	#Range: 4 ~ 100
	MaxColumns = 9
	#Horizontal alignment of the ingredient grid inside the available area
	#Allowed Values: LEFT, CENTER, RIGHT
	HorizontalAlignment = "LEFT"
	#Horizontal alignment of the ingredient grid inside the available area
	#Allowed Values: TOP, CENTER, BOTTOM
	VerticalAlignment = "TOP"
	#Visibility of the top page buttons. Use AUTO_HIDE to only show it when there are multiple pages.
	#Allowed Values: ENABLED, AUTO_HIDE, DISABLED
	ButtonNavigationVisibility = "ENABLED"
	#Set to true to draw a background texture behind the gui.
	DrawBackground = false
```
	
	
In-game config screen from Configured. 
	Clearly, here is something not plugged correctly. The file exists, obviously. 

![grafik](https://user-images.githubusercontent.com/106652912/225402317-d140bfc8-0422-4238-839d-6e64e7c8560b.png)
